/*
@TargetNode='SERVER2'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/07/2020 19:30:57
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-Service";
 Name = "SNMP-Service";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";
 Name = "SNMP-WMI-Provider";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
SourceInfo = "::18::13::Service";
 StartupType = "Automatic";
 ResourceID = "[Service]SNMP";
 Name = "SNMP";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 State = "Running";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
SourceInfo = "::131::17::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]RDS-RD-Server";
 Name = "RDS-RD-Server";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PackageResource as $MSFT_PackageResource1ref
{
SourceInfo = "::138::17::Package";
 Ensure = "Present";
 Path = "\\\\srv01\\Sources\\Prem\\soapsdk.msi";
 ResourceID = "[Package]Microsoft SOAP Toolkit 3.0";
 Name = "Microsoft SOAP Toolkit 3.0";
 ModuleName = "PsDesiredStateConfiguration";
 Arguments = "/quiet /qn /norestart";
 ProductId = "BCB4C18A-ACA6-4383-8688-E19933A705DD";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration1ref
{
SourceInfo = "::148::17::File";
 Ensure = "Present";
 ResourceID = "[File]exception.sites";
 DestinationPath = "C:\\Windows\\Sun\\Java\\Deployment\\security\\exception.sites";
 ModuleName = "PSDesiredStateConfiguration";
 Checksum = "ModifiedDate";
 MatchSource = True;
 Type = "File";
 SourcePath = "\\\\srv01\\sources\\Sun\\Java\\Deployment\\security\\exception.sites";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoInstaller as $cChocoInstaller1ref
{
InstallDir = "C:\\ProgramData\\Chocolatey";
 SourceInfo = "::160::13::cChocoInstaller";
 ModuleName = "cChoco";
 ModuleVersion = "2.4.1.0";
 ResourceID = "[cChocoInstaller]InstallChoco";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
SourceInfo = "::165::17::Registry";
 Ensure = "Present";
 ResourceID = "[Registry]HKEY_LOCAL_MACHINE\\SOFTWARE\\ExampleKey1";
 ValueData = {
    "TestData"
};
 ValueName = "TestValue";
 ModuleName = "PsDesiredStateConfiguration";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\ExampleKey1";
 ValueType = "ExpandString";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoPackageInstall as $cChocoPackageInstall1ref
{
SourceInfo = "::186::21::cChocoPackageInstaller";
 Ensure = "Absent";
 ResourceID = "[cChocoPackageInstaller]javaruntime";
 ModuleVersion = "2.4.1.0";
 Name = "javaruntime";
 Version = "8.0.60";
 ModuleName = "cChoco";

DependsOn = {
    "[cChocoInstaller]InstallChoco"};
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoPackageInstall as $cChocoPackageInstall2ref
{
SourceInfo = "::186::21::cChocoPackageInstaller";
 Ensure = "Present";
 ResourceID = "[cChocoPackageInstaller]7zip.install";
 ModuleVersion = "2.4.1.0";
 Name = "7zip.install";
 Version = "19.0";
 ModuleName = "cChoco";

DependsOn = {
    "[cChocoInstaller]InstallChoco"};
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoPackageInstall as $cChocoPackageInstall3ref
{
SourceInfo = "::178::21::cChocoPackageInstaller";
 Ensure = "Present";
 ResourceID = "[cChocoPackageInstaller]git";
 ModuleVersion = "2.4.1.0";
 Name = "git";
 Version = "2.28.0";
 ModuleName = "cChoco";
 chocoParams = "--params \"/GitAndUnixToolsOnPath /NoGitLfs /SChannel /NoAutoCrlf\"";

DependsOn = {
    "[cChocoInstaller]InstallChoco"};
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoPackageInstall as $cChocoPackageInstall4ref
{
SourceInfo = "::186::21::cChocoPackageInstaller";
 Ensure = "Present";
 ResourceID = "[cChocoPackageInstaller]microsoft-edge";
 ModuleVersion = "2.4.1.0";
 Name = "microsoft-edge";
 Version = "85.0.564.68";
 ModuleName = "cChoco";

DependsOn = {
    "[cChocoInstaller]InstallChoco"};
 ConfigurationName = "ConfigurationServer";
};
instance of cChocoPackageInstall as $cChocoPackageInstall5ref
{
SourceInfo = "::178::21::cChocoPackageInstaller";
 Ensure = "Present";
 ResourceID = "[cChocoPackageInstaller]powershell-core";
 ModuleVersion = "2.4.1.0";
 Name = "powershell-core";
 Version = "7.0.3";
 ModuleName = "cChoco";
 chocoParams = "--install-arguments=\"ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 REGISTER_MANIFEST=1 ENABLE_PSREMOTING=1\"";

DependsOn = {
    "[cChocoInstaller]InstallChoco"};
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/07/2020 19:30:57";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
