/*
@TargetNode='SERVER1'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/07/2020 19:30:57
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-Service";
 Name = "SNMP-Service";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";
 Name = "SNMP-WMI-Provider";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
SourceInfo = "::18::13::Service";
 StartupType = "Automatic";
 ResourceID = "[Service]SNMP";
 Name = "SNMP";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 State = "Running";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
SourceInfo = "::121::17::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]RDS-Connection-Broker";
 Name = "RDS-Connection-Broker";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource4ref
{
SourceInfo = "::121::17::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]RDS-Licensing";
 Name = "RDS-Licensing";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/07/2020 19:30:57";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
