/*
@TargetNode='SERVER1'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/04/2020 13:16:19
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::10::13::WindowsFeature";
 Name = "SNMP-Service";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]SNMP-Service";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::10::13::WindowsFeature";
 Name = "SNMP-WMI-Provider";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::18::13::Service";
 Name = "SNMP";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Service]SNMP";
 State = "Running";
 StartupType = "Automatic";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateySoftware as $ChocolateySoftware1ref
{
InstallationDirectory = "C:\\ProgramData\\Chocolatey";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::141::9::ChocolateySoftware";
 ModuleVersion = "0.0.79";
 ModuleName = "chocolatey";
 Ensure = "Present";
 ChocoTempDir = "https://chocolatey.org/api/v2";
 ResourceID = "[ChocolateySoftware]ChocoInst";
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateySource as $ChocolateySource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::148::9::ChocolateySource";
 ModuleVersion = "0.0.79";
 Source = "C:\\Users\\LAUREN~1.LIE\\AppData\\Local\\Temp\\Chocolatey";
 ModuleName = "chocolatey";
 Ensure = "Present";
 Name = "Chocolatey";
 Priority = 0;
 ResourceID = "[ChocolateySource]ChocolateyOrg";
 Disabled = False;

DependsOn = {
    "[ChocolateySoftware]ChocoInst"};
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/04/2020 13:16:19";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
