/*
@TargetNode='SERVER2'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/06/2020 08:34:39
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ModuleName = "PsDesiredStateConfiguration";
 Name = "SNMP-Service";
 ResourceID = "[WindowsFeature]SNMP-Service";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::17::13::WindowsFeature";

ModuleVersion = "0.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
ModuleName = "PsDesiredStateConfiguration";
 Name = "SNMP-WMI-Provider";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::17::13::WindowsFeature";

ModuleVersion = "0.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
ModuleName = "PsDesiredStateConfiguration";
 Name = "SNMP";
 State = "Running";
 ResourceID = "[Service]SNMP";
 Ensure = "Present";
 StartupType = "Automatic";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::25::13::Service";

ModuleVersion = "0.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
ModuleName = "PsDesiredStateConfiguration";
 Name = "RDS-RD-Server";
 ResourceID = "[WindowsFeature]RDS_RDS-RD-Server";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::185::17::WindowsFeature";

ModuleVersion = "0.0";
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateySoftware as $ChocolateySoftware1ref
{
ChocoTempDir = "C:\\temp\\Chocolatey";
 ModuleName = "chocolatey";
 ModuleVersion = "0.0.79";
 ResourceID = "[ChocolateySoftware]ChocoInst";
 InstallationDirectory = "C:\\ProgramData\\Chocolatey";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::193::13::ChocolateySoftware";
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateySource as $ChocolateySource1ref
{
ModuleName = "chocolatey";
 Name = "Chocolatey";
 ModuleVersion = "0.0.79";
 Priority = 0;
 ResourceID = "[ChocolateySource]ChocolateyOrg";
 Source = "https://chocolatey.org/api/v2";
 Disabled = False;
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::200::13::ChocolateySource";

DependsOn = {
    "[ChocolateySoftware]ChocoInst"};
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateyPackage as $ChocolateyPackage1ref
{
ModuleName = "chocolatey";
 Name = "javaruntime";
 ModuleVersion = "0.0.79";
 ResourceID = "[ChocolateyPackage]javaruntime";
 ChocolateyOptions = NULL;
 Version = "8.0.60";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::211::17::ChocolateyPackage";

DependsOn = {
    "[ChocolateySoftware]ChocoInst"};
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateyPackage as $ChocolateyPackage2ref
{
ModuleName = "chocolatey";
 Name = "7zip.install";
 ModuleVersion = "0.0.79";
 ResourceID = "[ChocolateyPackage]7zip.install";
 ChocolateyOptions = NULL;
 Version = "19.0";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::211::17::ChocolateyPackage";

DependsOn = {
    "[ChocolateySoftware]ChocoInst"};
 ConfigurationName = "ConfigurationServer";
};
instance of ChocolateyPackage as $ChocolateyPackage3ref
{
ModuleName = "chocolatey";
 Name = "git";
 ModuleVersion = "0.0.79";
 ResourceID = "[ChocolateyPackage]git";
 ChocolateyOptions = NULL;
 Version = "2.28.0";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::211::17::ChocolateyPackage";

DependsOn = {
    "[ChocolateySoftware]ChocoInst"};
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/06/2020 08:34:39";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
