/*
@TargetNode='SRV01'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/07/2020 19:30:57
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-Service";
 Name = "SNMP-Service";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
SourceInfo = "::10::13::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";
 Name = "SNMP-WMI-Provider";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
SourceInfo = "::18::13::Service";
 StartupType = "Automatic";
 ResourceID = "[Service]SNMP";
 Name = "SNMP";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 State = "Running";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule1ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]PSDesiredStateConfiguration";
 ModuleVersion = "2.2.5";
 Name = "PSDesiredStateConfiguration";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule2ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]chocolatey";
 ModuleVersion = "2.2.5";
 Name = "chocolatey";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule3ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]ComputerManagementDsc";
 ModuleVersion = "2.2.5";
 Name = "ComputerManagementDsc";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule4ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]SqlServerDsc";
 ModuleVersion = "2.2.5";
 Name = "SqlServerDsc";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule5ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]ActiveDirectoryDsc";
 ModuleVersion = "2.2.5";
 Name = "ActiveDirectoryDsc";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_PSModule as $MSFT_PSModule6ref
{
SourceInfo = "::38::17::PSModule";
 Ensure = "Present";
 ResourceID = "[PSModule]cChoco";
 ModuleVersion = "2.2.5";
 Name = "cChoco";
 ModuleName = "PowerShellGet";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration1ref
{
SourceInfo = "::55::13::File";
 Ensure = "Present";
 ResourceID = "[File]RepTest";
 DestinationPath = "C:\\Test";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration2ref
{
SourceInfo = "::61::13::File";
 Ensure = "Present";
 ResourceID = "[File]RepConfiguration";
 DestinationPath = "C:\\Test\\Configuration";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration3ref
{
SourceInfo = "::68::13::File";
 Ensure = "Present";
 ResourceID = "[File]RepMOFFiles";
 DestinationPath = "C:\\Test\\MOFFiles";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration4ref
{
SourceInfo = "::75::13::File";
 Ensure = "Present";
 ResourceID = "[File]RepLCMFiles";
 DestinationPath = "C:\\Test\\LCMFiles";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration5ref
{
SourceInfo = "::82::13::File";
 Ensure = "Present";
 ResourceID = "[File]RepSources";
 DestinationPath = "C:\\Sources";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of DSC_SmbShare as $DSC_SmbShare1ref
{
SourceInfo = "::88::13::SmbShare";
 Description = "Sources d'installation";
 Path = "C:\\Sources";
 ResourceID = "[SmbShare]RepSources";
 ModuleVersion = "8.4.0";
 Name = "Sources";
 ModuleName = "ComputerManagementDsc";
 FullAccess = {
    "Everyone"
};
 Ensure = "Present";

DependsOn = {
    "[File]RepSources"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
SourceInfo = "::102::17::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]AD-Domain-Services";
 Name = "AD-Domain-Services";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource4ref
{
SourceInfo = "::102::17::WindowsFeature";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]RSAT-AD-PowerShell";
 Name = "RSAT-AD-PowerShell";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource2ref
{
SourceInfo = "::110::17::Service";
 StartupType = "Automatic";
 ResourceID = "[Service]DNS";
 Name = "DNS";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 State = "Running";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource3ref
{
SourceInfo = "::110::17::Service";
 StartupType = "Automatic";
 ResourceID = "[Service]NTDS";
 Name = "NTDS";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 State = "Running";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/07/2020 19:30:57";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
