/*
@TargetNode='SRV01'
@GeneratedBy=Laurent.Lienhard
@GenerationDate=10/04/2020 13:16:19
@GenerationHost=PORT9999
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::10::13::WindowsFeature";
 Name = "SNMP-Service";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]SNMP-Service";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::10::13::WindowsFeature";
 Name = "SNMP-WMI-Provider";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]SNMP-WMI-Provider";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::18::13::Service";
 Name = "SNMP";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Service]SNMP";
 State = "Running";
 StartupType = "Automatic";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::32::13::WindowsFeature";
 Name = "AD-Domain-Services";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]AD-Domain-Services";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_RoleResource as $MSFT_RoleResource4ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::32::13::WindowsFeature";
 Name = "RSAT-AD-PowerShell";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[WindowsFeature]RSAT-AD-PowerShell";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of PSModuleResource as $PSModuleResource1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::40::13::PSModuleResource";
 ModuleVersion = "0.3";
 Module_Name = "PSDesiredStateConfiguration";
 Ensure = "present";
 ModuleName = "PowerShellModule";
 ResourceID = "[PSModuleResource]PSDesiredStateConfiguration";
 InstallScope = "allusers";
 ConfigurationName = "ConfigurationServer";
};
instance of PSModuleResource as $PSModuleResource2ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::40::13::PSModuleResource";
 ModuleVersion = "0.3";
 Module_Name = "chocolatey";
 Ensure = "present";
 ModuleName = "PowerShellModule";
 ResourceID = "[PSModuleResource]chocolatey";
 InstallScope = "allusers";
 ConfigurationName = "ConfigurationServer";
};
instance of PSModuleResource as $PSModuleResource3ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::40::13::PSModuleResource";
 ModuleVersion = "0.3";
 Module_Name = "ComputerManagementDsc";
 Ensure = "present";
 ModuleName = "PowerShellModule";
 ResourceID = "[PSModuleResource]ComputerManagementDsc";
 InstallScope = "allusers";
 ConfigurationName = "ConfigurationServer";
};
instance of PSModuleResource as $PSModuleResource4ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::40::13::PSModuleResource";
 ModuleVersion = "0.3";
 Module_Name = "SqlServerDsc";
 Ensure = "present";
 ModuleName = "PowerShellModule";
 ResourceID = "[PSModuleResource]SqlServerDsc";
 InstallScope = "allusers";
 ConfigurationName = "ConfigurationServer";
};
instance of PSModuleResource as $PSModuleResource5ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::40::13::PSModuleResource";
 ModuleVersion = "0.3";
 Module_Name = "ActiveDirectoryDsc";
 Ensure = "present";
 ModuleName = "PowerShellModule";
 ResourceID = "[PSModuleResource]ActiveDirectoryDsc";
 InstallScope = "allusers";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource2ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::49::13::Service";
 Name = "DNS";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Service]DNS";
 State = "Running";
 StartupType = "Automatic";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource3ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::49::13::Service";
 Name = "NTDS";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Service]NTDS";
 State = "Running";
 StartupType = "Automatic";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::57::9::File";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";
 Ensure = "Present";
 ResourceID = "[File]RepTest";
 DestinationPath = "C:\\Test";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration2ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::63::9::File";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";
 Ensure = "Present";
 ResourceID = "[File]RepConfiguration";
 DestinationPath = "C:\\Test\\Configuration";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration3ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::70::9::File";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";
 Ensure = "Present";
 ResourceID = "[File]RepMOFFiles";
 DestinationPath = "C:\\Test\\MOFFiles";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration4ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::77::9::File";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";
 Ensure = "Present";
 ResourceID = "[File]RepLCMFiles";
 DestinationPath = "C:\\Test\\LCMFiles";

ModuleVersion = "1.0";
DependsOn = {
    "[File]RepTest"};
 ConfigurationName = "ConfigurationServer";
};
instance of MSFT_FileDirectoryConfiguration as $MSFT_FileDirectoryConfiguration5ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::84::9::File";
 ModuleName = "PSDesiredStateConfiguration";
 Type = "Directory";
 Ensure = "Present";
 ResourceID = "[File]RepSources";
 DestinationPath = "C:\\Sources";

ModuleVersion = "1.0";
 ConfigurationName = "ConfigurationServer";
};
instance of DSC_SmbShare as $DSC_SmbShare1ref
{
SourceInfo = "C:\\Users\\Laurent.Lienhard\\OneDrive\\01-DEV\\TestDsc\\03_AvecConfigurationDataFile\\ConfigurationServer.ps1::90::9::SmbShare";
 ModuleVersion = "8.4.0";
 Path = "C:\\Sources";
 Name = "Sources";
 Ensure = "Present";
 FullAccess = {
    "Everyone"
};
 ModuleName = "ComputerManagementDsc";
 Description = "Sources d'installation";
 ResourceID = "[SmbShare]RepSources";

DependsOn = {
    "[File]RepSources"};
 ConfigurationName = "ConfigurationServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Laurent.Lienhard";

                        GenerationDate="10/04/2020 13:16:19";

                        GenerationHost="PORT9999";

                        Name="ConfigurationServer";

                    };
